### PR TITLE
Fixed tensorflow and added some description about the fork.

### PR DESCRIPTION
**Pull request by iklevente-zz**
Because of tensorflow my AMD GPU based PC couldn't start the program. It was constantly looking for CUDA. I edited the requirements.txt to the CPU only version of tensorflow, so now the program starts.
I also added some description to your fork so new users can understand why did you make this fork.

### CODE REVIEW

**Comment by iklevente-zz** [comment]
https://github.com/ByPort/Real-Time-Voice-Cloning/pull/1 --> @daugihao had the same problem. His method is good too, but there is a newer, separated CPU only version which also works: `tensorflow==1.15`.

**Comment by jmsgrgry** [comment]
I actually got this to work, thank you! But I can't import video files, I can only record. When I try to upload I get "Warning: you did not pass a root directory for datasets as argument." Any clue what to do?

**Comment by jamespart2** [comment]
This worked on my GPUless ultraportable! Thanks so much!

**Comment by ByPort** [comment]
Merged. Thanks for your contribution! Sorry for the laaaaaate response, never checked GitHub notifications before.

**Pull request merged**
